id: IC5EE44A4
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2021-09-28T05:18:40+00:00'
last_modified: '2022-06-13T12:55:14.973368+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W8LS22914
  title: ཐེག་པ་ཆེན་པོ་བློ་སྦྱོང་བརྒྱ་རྩ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    F1E0:
      image_group_id: I8LS22916
      title: ''
      total_pages: ''
      order: 1
      base_file: F1E0.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
